name = "NMRScreen"
uuid = "e6af4f88-7701-4df4-8af7-4e9c6957a0a0"
authors = ["Chris Waudby <c.waudby@ucl.ac.uk> and contributors"]
version = "0.0.4"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
MolecularGraph = "6c89ec66-9cd8-5372-9f91-fabc50dd27fd"
NMRTools = "c2839fe3-f1de-42fc-897f-c1b0e8db4db6"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
RDKitMinimalLib = "44044271-7623-48dc-8250-42433c44e4b7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UMAP = "c4f8c510-2410-5be4-91d7-4fbaeb39457e"

[compat]
CairoMakie = "0.13.10"
Distances = "0.10.12"
FileIO = "1.17.1"
GLMakie = "0.11.11"
LinearAlgebra = "1.11.0"
LsqFit = "0.15.1"
Measurements = "2.14.0"
MolecularGraph = "0.17.1"
NMRTools = "0.1.13"
Peaks = "0.5.3"
RDKitMinimalLib = "1.2.0"
Statistics = "1.11.1"
TOML = "1.0.3"
UMAP = "0.1.11"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
